name: Lookub+
version: 0.0.1
author: DeadSAGA
main: mainPackage.mainClass
commands:
  test:
    description: 
    permission: test.use
  alert:
    description: 
    permission: bc.use
  kit:
    description:
    permission: kit.use
  plugins:
    description:
    permission: plugins.use
  pl:
    description:
    permission: plugins.use
  spawn:
    description:
  rtp:
    description: